on: push

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - architecture: amd64-unknown-linux-gnu
            platform: linux/amd64
            use-cross: false
          - architecture: aarch64-unknown-linux-gnu
            platform: linux/arm64/v8
            use-cross: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker metadata
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            event=tag,type=semver,pattern={{version}}
            event=tag,type=semver,pattern={{major}}.{{minor}}
            event=tag,type=semver,pattern={{major}}
            type=sha

      - name: Setup rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly

      - name: Install cross
        if: matrix.use-cross
        uses: taiki-e/install-action@v2
        with:
          tool: cross

      - name: Rust build
        run: cargo +nightly build --release -Z sparse-registry --target ${{ matrix.architecture }}

      - name: Docker Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          platforms: ${{ matrix.platform }}
          builder: ${{ steps.buildx.outputs.name }}
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
