on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker metadata
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            event=tag,type=semver,pattern={{version}}
            event=tag,type=semver,pattern={{major}}.{{minor}}
            event=tag,type=semver,pattern={{major}}
            type=sha

      - name: Docker Build and push
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64,linux/arm64/v8
          push: true
          # replace above with this: ${{ github.ref == 'refs/heads/main' }} || startsWith(github.ref, 'refs/tags/v')
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}

  build-no-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release -Z sparse-registry --timings
